### ISSUE TITLE
IndexError in dataset class when iter > number of class images

### ISSUE THREAD

**Issue by chaserhkj** [CCRcmcpe/scal-sdt#4]
Got this when I am trying the [dog example from huggingface](https://huggingface.co/docs/diffusers/training/dreambooth):

```
Original Traceback (most recent call last):
  File "/home/hkj/.pyenv/versions/scal-sdt/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hkj/.pyenv/versions/scal-sdt/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hkj/.pyenv/versions/scal-sdt/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hkj/DreamBooth/scal-sdt/modules/dataset/datasets.py", line 214, in __getitem__
    class_ = self.class_set[index[1]]
  File "/home/hkj/DreamBooth/scal-sdt/modules/dataset/datasets.py", line 66, in __getitem__
    path = self.image_paths[index.value]
IndexError: list index out of range
```

The error happened around Epoch 20, and I have 5 instance images and 100 class images. So the crash happened around iter = 100. It seems that it crashed because it didn't have enough class images to use.

Maybe we need to do the mod on indexes like [here](https://github.com/CCRcmcpe/diffusers/blob/main/examples/dreambooth/modules/datasets.py#L99) for class images in scal-sdt as well?

**Comment by CCRcmcpe** [comment]
Is ARB enabled?
